name: CI

on: push

jobs:
  allt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"
          cache: "pip"
      - run: pip install -e ".[dev]"
      - run: python -m churn.model
      - run: pytest

      #test with cache 2